env:
  browser: false
  es2021: true
ignorePatterns:
  - ci
  - dist
  - coverage
extends:
  - eslint:recommended
  - plugin:import/typescript
  - plugin:@typescript-eslint/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
